# Generated by cucumber-sinatra. (2014-11-14 11:39:37 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/rps.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = RockPapepScissors

class RockPapepScissorsWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  RockPapepScissorsWorld.new
end
